Repository terasolunaorg/terasoluna-gfw-functionaltest, pull requests merged in 2019-03, with the labels that each got.

#774 apply htmlunit driver and various webdriver #626
  terasoluna-gfw-functionaltest-selenium/pom.xml
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/ChromeDriverFactoryBean.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/FirefoxDriverFactoryBean.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/HtmlUnitDriverEx.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/WebDriverManagerFactoryBean.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/WebDriverType.java
  terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/selenium.properties
  terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
Labels: status: in-progress, type: improvement, version: 5.5.1

#775 correct typo #626
  terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
Labels: status: in-progress, version: 5.5.1

#777 apply @ByteSize #776
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationForm.java
  terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/bytesize.jsp
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/index.jsp
Labels: status: in-progress, type: new-feature, version: 5.5.1

#782 update jdbc driver #781
  pom.xml
  terasoluna-gfw-functionaltest-domain/pom.xml
  terasoluna-gfw-functionaltest-initdb/pom.xml
Labels: status: in-progress, version: 5.5.1

#786 make reloadable codelist immutable #784
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/10_02_form.jsp
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
Labels: status: in-progress, type: bug, version: 5.5.1

#787 new feature reloadable i18n codelist #785
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/I18nItemCode.java
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/repository/codelist/I18nCodeListRepository.java
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/I18nCodeListService.java
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/I18nCodeListServiceImpl.java
  terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/I18nCodeListForm.java
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/12_01_form.jsp
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
Labels: status: in-progress, type: new-feature, version: 5.5.1

#789 resolve deprecated api #788
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/PageSource.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/el/ElMapOfSimpleValueDefaultTrimController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/message/MessageController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow1Controller.java
Labels: status: in-progress, type: improvement, version: 5.5.1

#791 Change to use prefer-application-packages #790
  terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/webapp/WEB-INF/weblogic.xml
Labels: status: in-progress, type: new-feature, version: 5.5.1

#792 [5.4.x] apply @ByteSize #776
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationForm.java
  terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/bytesize.jsp
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/index.jsp
Labels: status: in-progress, type: new-feature, version: 5.4.2

#794 [5.4.x] make reloadable codelist immutable #784
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/10_02_form.jsp
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
Labels: status: in-progress, type: bug, version: 5.4.2
