Repository terasolunaorg/terasoluna-gfw-functionaltest, pull requests merged in 2019-12, with the labels that each got.

#829 [5.5.x] Change Oracle JDK -> Open JDK #814 Adapt xvfb usage at Xenial environment #813 Suppress log output #819
  .travis.yml
Labels: difficulity: mid, priority: high, type: misc, version: 5.5.2

#830 [5.4.x] Suppress log output #819 Fix Travis CI environment for Trusty #814
  .travis.yml
Labels: difficulity: mid, priority: high, type: improvement, type: misc, version: 5.4.2

#831 [5.3.x] Suppress log output #819 Fix Travis CI environment for Trusty #814
  .travis.yml
Labels: difficulity: mid, priority: high, type: improvement, type: misc, version: 5.3.3

#832 [5.2.x] Suppress log output #819 Fix Travis CI environment for Trusty #814
  .travis.yml
Labels: difficulity: mid, priority: high, type: improvement, type: misc, version: 5.2.2

#833 [5.1.x] Suppress log output #819 Fix Travis CI environment for Trusty #814
  .travis.yml
Labels: difficulity: mid, priority: high, type: improvement, type: misc, version: 5.1.2

#834 [5.0.x] Suppress log output #819 Fix Travis CI environment for Trusty #814
  .travis.yml
Labels: difficulity: mid, priority: high, type: improvement, type: misc, version: 5.0.3

#835 [1.0.x] Suppress log output #819 Fix Travis CI environment for Trusty #814
  .travis.yml
Labels: difficulity: mid, priority: high, type: improvement, type: misc, version: 1.0.7

#827 add innerElementClass attribute to pagination tag. #826
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationController.java
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/pagination/index.jsp
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/pagination/innerElementClass.jsp
  terasoluna-gfw-functionaltest-web/src/main/webapp/resources/app/css/style.css
Labels: type: improvement
