Repository terasolunaorg/terasoluna-gfw-functionaltest, pull requests merged in 2019-01, with the labels that each got.

#757 add Exception handling #740
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WaitWebDriverEventListener.java
Labels: status: in-progress

#766 apply spring boot dependencies 2.1.2 #761 #762 #763
  .travis.yml
  pom.xml
  terasoluna-gfw-functionaltest-domain/pom.xml
  terasoluna-gfw-functionaltest-env/pom.xml
  terasoluna-gfw-functionaltest-initdb/pom.xml
  terasoluna-gfw-functionaltest-selenium/pom.xml
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
  terasoluna-gfw-functionaltest-web/pom.xml
Labels: status: in-progress, type: new-feature, version: 5.5.1

#767 fix build profile of terasoluna-gfw #762
  .travis.yml
Labels: status: in-progress, type: improvement, version: 5.5.1

#768 update selenium 3.14.0 + webdrivermanager 3.1.1 #740
  .travis.yml
  README.md
  pom.xml
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WaitWebDriverEventListener.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverEventListenerAdapter.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverManagerFactoryBean.java
  terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
  terasoluna-gfw-functionaltest-selenium/src/test/resources/wdm.properties
Labels: status: in-progress, type: new-feature, version: 5.5.1

#765 Modify the way to set thredhold time of TraceLoggingInterceptor #764
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
Labels: status: in-progress
