Repository terasolunaorg/terasoluna-gfw-functionaltest, pull requests merged in 2019-04, with the labels that each got.

#796 udpate to 5.5.2-SNAPSHOT #795
  .travis.yml
  pom.xml
  terasoluna-gfw-functionaltest-domain/pom.xml
  terasoluna-gfw-functionaltest-env/pom.xml
  terasoluna-gfw-functionaltest-initdb/pom.xml
  terasoluna-gfw-functionaltest-selenium/pom.xml
  terasoluna-gfw-functionaltest-web/pom.xml
Labels: status: in-progress

#797 update to 5.6.0-SNAPSHOT #795
  ISSUE_TEMPLATE.md
  pom.xml
  terasoluna-gfw-functionaltest-domain/pom.xml
  terasoluna-gfw-functionaltest-env/pom.xml
  terasoluna-gfw-functionaltest-initdb/pom.xml
  terasoluna-gfw-functionaltest-selenium/pom.xml
  terasoluna-gfw-functionaltest-web/pom.xml
Labels: status: in-progress

#798 [5.4.x] new feature reloadable i18n codelist #785
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/I18nItemCode.java
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/repository/codelist/I18nCodeListRepository.java
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/I18nCodeListService.java
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/I18nCodeListServiceImpl.java
  terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/I18nCodeListForm.java
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/12_01_form.jsp
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
Labels: status: in-progress, type: new-feature, version: 5.4.2

#799 update jdbc driver #781
  pom.xml
  terasoluna-gfw-functionaltest-domain/pom.xml
  terasoluna-gfw-functionaltest-initdb/pom.xml
Labels: status: in-progress, version: 5.4.2

#801 Make the validator compliant with Bean Validation 2.0 #800
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/InfoLogging.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInSampleCodeList.java
Labels: status: in-progress, type: new-feature, version: 5.6.0

#802 [5.5.x] Make the validator compliant with Bean Validation 2.0 #800
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/InfoLogging.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInSampleCodeList.java
Labels: status: in-progress, type: new-feature, version: 5.5.1

#808 [5.4.x] replace schema location for spring from http to https #807
  terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml
  terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-domain.xml
  terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.xml
  terasoluna-gfw-functionaltest-domain/src/test/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra-mybatis.xml
  terasoluna-gfw-functionaltest-domain/src/test/resources/test-context.xml
  terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
  terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml
  terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml
Labels: status: in-progress

#806 Addition of difference with Selenium update fix #740
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java
  terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
Labels: status: in-progress

#803 [5.4.x] Make the validator compliant with Bean Validation 1.1 #800
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/InfoLogging.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInSampleCodeList.java
Labels: status: in-progress, type: improvement, version: 5.4.2

#804 [5.4.x] resolve deprecated api #788
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/PageSource.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/el/ElMapOfSimpleValueDefaultTrimController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/message/MessageController.java
  terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow1Controller.java
Labels: status: in-backport, type: improvement, version: 5.4.2
