Repository terasolunaorg/terasoluna-gfw-functionaltest, pull requests merged in 2020-03, with the labels that each got.

#851 fix logback settings #837
  terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/logback.xml
  terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
Labels: type: improvement, version: 5.6.0

#853 fix logger name #852
  terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/DBLogCleaner.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java
  terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java
Labels: type: bug, version: 5.6.0

#854 change loglevel of Repository to trace to log ResultSet #837
  terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/logback.xml
  terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/logback.xml
  terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
Labels: version: 5.6.0
